package.json
test.js

Supporting [eslint-config-xo #3](https://github.com/sindresorhus/eslint-config-xo/pull/3).
I took the time to update `ava` and the dev `xo` as well...

Using babel-eslint as parser for esnext

---

cli.js

pass options to lintText from cli

---

readme.md

Ref https://github.com/scrooloose/syntastic/pull/1561
Fixes gh-28

Add documentation about using XO with Vim

---

readme.md

Correct a broken link on the readme file.

fix broken link for ignored paths

---

readme.md

Adding metalsmith-xo to Build Systems

---

cli.js
index.js
options-manager.js
test/options-manager.js

Mostly white space fixes for consistency.

Code style tweaks

---

index.js
options-manager.js
test/options-manager.js

I haven't explored why I was doing it the way I was, but this passes all the tests.

[WIP]: fix option handling.

---

contributing.md
readme.md

- fix typo in `contributing.md` file
- fix broken link to babel experimental features in `readme.md` file

Fix documentation

---

cli.js
readme.md
test/cli.js

Add support for auto-fixing code from stdin

---

config/plugins.js

See https://github.com/babel/eslint-plugin-babel/issues/59
Depends/related https://github.com/sindresorhus/eslint-config-xo/pull/38

Don't trigger duplication errors for Flow type imports

---

cli.js
index.js
options-manager.js

Just some things I've to stumble upon during #195 review.

Minor code style tweaks

---

options-manager.js
test/options-manager.js

Thanks for identifying the fault and providing the fix @schnittstabil. 
* backport from #200

Force posix formatted paths for parsed ignore patterns

---

readme.md

options-manager.js → lib/options-manager.js in https://github.com/sindresorhus/xo/commit/0c6dbf50f5e23dc3f7a87b3a52d957dcf5d9ca2a

Update the `options-manager.js` path in the readme

---

lib/options-manager.js
package.json

Use `lodash.mergewith` instead of `deep-assign`

---

readme.md

- Add [xo-summary](https://github.com/LitoMore/xo-summary) to readme

Add related package to readme

---

lib/options-manager.js
readme.md
test/options-manager.js

Make Prettier confing take precedence over XO

---

lib/options-manager.js
test/options-manager.js

Disable number-literal-case rule when using Prettier

---

main.js
test/fixtures/default-options/package.json
test/main.js

Do not override default options with absent CLI flags

---

lib/options-manager.js
test/options-manager.js

Fix `space`/`useTabs` conflict message

---

config/plugins.js
package.json

https://mysticatea.github.io/eslint-plugin-eslint-comments/rules/
FYI, @mysticatea :)

Add `eslint-plugin-eslint-comments` ESLint plugin

---

lib/options-manager.js

Add `tap-snapshots/*.js` to default ignore list

---

readme.md

Mention eslint-config-xo-vue in the readme

---

lib/open-report.js

refactored the respective code block to eliminate redundancy.

Minor code refactor

---

test/lint-files.js

Working branch to test fixes for failed CI on windows:
https://github.com/xojs/xo/pull/377#issuecomment-535084558

Fix lint test error on Windows

---

config/plugins.js

Improve `import/no-unassigned-import` settings

---

package.json

Per https://github.com/xojs/xo/pull/431#issuecomment-591052196

Add `typescript` as a dependency

---

lib/options-manager.js
test/options-manager.js

Set `indent` rule for TS files too

---

package.json

Fix #441
Turns out no API changes in Prettier is impacting us.

Upgrade to Prettier 2.0.4

---

lib/options-manager.js
test/cli-main.js
test/fixtures/custom-extension/one-space.mjs

fixes bullet-point 2 in https://github.com/xojs/xo/issues/447

Fix the `extensions` option

---

readme.md

I wasted a bit of time getting annotations on Actions to work today; I think this is important enough to include in the documentation.

Clarify usage on Github Actions

---

lib/options-manager.js
test/options-manager.js

Fix handling of `parserOptions` for TypeScript

---

lib/options-manager.js
test/options-manager.js

Make cache directory be relative to cwd

---

lib/constants.js
lib/options-manager.js
test/options-manager.js
test/options.js

Improve Prettier config

---

readme.md

Sorry, I accidentally removed it in #591.

Fix accidentally removed readme text

---

readme.md

Follow-up of https://github.com/xojs/xo/pull/660.

Replace link `node` with `n`

---

readme.md

Ref: https://github.com/eslint-community/eslint-plugin-n/issues/8

Update link to `n` ESLint plugin

---

config/plugins.cjs

add default groups to import/order rule

---

readme.md

Resolves https://github.com/xojs/xo/issues/739

docs(README): added typescript extensions

---

readme.md

- `#L1` would not be appropriate so just refer `lib/constant.ts` 
- Add a link to "ignores" section.

Small tweaks on readme

---

lib/xo-to-eslint.ts
test/xo-to-eslint.test.ts

fix: ensure prettier rules are applied last

---

lib/xo-to-eslint.ts
lib/xo.ts
test/xo-to-eslint.test.ts

the `xoToEslintConfig` function is needlessly async

Remove unneeded async create config

---

cli.ts
readme.md

Made the description of the quiet option appear when executing the `xo --help` command.

Add description of quiet cli option

---

lib/handle-ts-files.ts
lib/xo.ts
test/cli.test.ts

Fix cache dir before linting
