readme.md

VSCode plugins are not yet publicly available but will be soon. This plugin adds XO linting to the editor.

Added vscode editor plugin

---

cli.js
index.js
package.json
readme.md
test.js

Don't know if you had another API in mind, but this at least does the job. If you want, I can include https://github.com/dustinspecker/eslint-plugin-no-use-extend-native/ by default too (like mentioned in #30).
Fixes #30.

Add support for plugins

---

index.js
package.json
test.js

Prevents use of extended native objects.

Use `no-use-extend-native` plugin by default

---

package.json

I updated this plugin in a local version of XO and ran XO on AVA and Pageres without any issues/false positives. This plugin is also being used on all of my repos. *Hopefully*, there aren't any more false positives.
I didn't re-enable the plugin - figured that's up to the XO team.

Bump no-use-extend-native to 0.3.1

---

cli.js
readme.md

This PR fixes #38.
When `xo` is invoked with `--open` option, it automatically opens files with issues in a user's preferred editor (by checking `$EDITOR` environment variable):
```bash
$ xo --open
```
If `$EDITOR` is empty:

Open files with issues in an editor

---

index.js

If the `esnext` option is `false`, we currently blow away existing
plugins, replacing it with only the `babel` plugin. This prepends it.
This does not come with a test, as option handling is currently pretty difficult.
We can add the appropriate test for this there.
Reference:
https://github.com/sindresorhus/xo/pull/58#discussion_r47583285

Don't destroy plugins.

---

options-manager.js
test/options-manager.js

Custom rules like 
```js
"babel/object-curly-spacing": [2, "always"]
```
are no longer ignored, as they are merged after defaults are determined.

Merge custom rules after defaults are determined

---

.gitignore
test/cli.js
test/fixtures/project/file.js
test/fixtures/project/node_modules/eslint-config-custom/config.json
test/fixtures/project/node_modules/eslint-config-custom/package.json
test/fixtures/project/package.json

PR to demonstrate https://github.com/sindresorhus/xo/issues/71#issuecomment-191247202. The test project is in `test/fixtures/project`.

Demo broken shareable configs

---

config/plugins.js
package.json

As [per request](https://github.com/sindresorhus/module-requests/issues/62#issuecomment-201326964), this adds eslint-plugin-import-order to the list of plugins.
Let me know if and where I need to add tests, as I could not find related ones.

Add eslint-plugin-import-order to plugins

---

readme.md

Hello.
I made an emacs package that provide some level of integration between xo and emacs.
It has been accepted and published to [MELPA](https://melpa.org/) which is a well-known emacs package repository.
I figured it would be a good idea to reference it over here too. :)
Let me know if there's anything you wanna know.

add reference to emacs package

---

options-manager.js

Hello @sindresorhus,
I have to work on this JSX project that insists on 4 space tabs, but discovered that `xo`'s `--space` flag wasn't overriding the JSX indentation set by `eslint-config-xo-react`.
This PR overrides the JSX spacing rules when the `--space` flag is used.
Thanks!

Make `--spaces` apply to JSX (i.e., override `eslint-config-xo-react`).

---

cli.js
config/plugins.js
package.json
test/fixtures/overrides/package.json

https://github.com/benmosher/eslint-plugin-import (@benmosher fyi)
-
@jamestalmage @novemberborn @vdemedes @kevva @SamVerschueren @jfmengels  and anyone looking. I could use some help with testing this. Git checkout out this PR locally, `npm link` it globally, and run `xo --no-local` on your projects to see if there are any problems (not lint violation, unless it's wrong).
-
Known issues:
*(Help welcome for those)*

add `eslint-plugin-import`

---

cli.js
index.js
readme.md
test/cli.js

Fix for https://github.com/sindresorhus/xo/issues/125

add --quiet feature

---

index.js
options-manager.js
package.json
test/api.js
test/fixtures/overrides/package.json

fixes sindresorhus/atom-linter-xo#20
This was really annoying me.

find and use overrides opts in lintText

---

cli.js
index.js
options-manager.js
readme.md
test/api.js
test/options-manager.js

Solves #117 (Allowing more file extensions)
Trying to detect whether the glob pattern restricts file extensions quickly gets out of hand. There are arrays of patterns, there can be negations, obscure regex syntax that may not be accounted for and that does limit what extensions can be used...
So, I added a new option: anyExtension (or --any-extension).
Set it to true, and the extension filter is disabled.
In my opinion, it would be better to just remove it altogether. Most people are probably just using the default expression and the ignores option, so impact should be minimal. A FAQ entry would be fine. Maybe this should happen for 1.0?

Add `extensions` option

---

options-manager.js
readme.md
test/options-manager.js

Add `settings` and `parser` options

---

options-manager.js
readme.md
test/options-manager.js

XO allows to specify sharable configs to override any of the default rules [link](https://github.com/sindresorhus/xo#extends). However, in ESLint it is allowed to use configs shared by plugins (prefixed with `eslint-plugin-`, next to shared configs (prefixed with `eslint-config-` and absolute/relative paths. These plugin configs are prefixed with `plugin:`, [see here](http://eslint.org/docs/user-guide/configuring#using-the-configuration-from-a-plugin).
This PR allows to specify such plugin configs in the XO configuration, by checking whether the name starts with `plugin:` and only prepending `eslint-config-` if that is not the case.

Support plugin config in the `extends` option

---

readme.md

Instructions to use XO within [vim-autoformat](https://github.com/Chiel92/vim-autoformat) (related to #163).

document xo's usage from vim-autoformat

---

index.js
package.json
test/api.js

- add multimatch-powered short-circuit to `lintText`
- add supporting test cases
- throw for opts.ignores without opts.filename
-  use default ignores when opts.filename is given
- closes #168
BREAKING CHANGES:
* lintText now uses the same default ignores as lintFiles with opts.filename
* **/node_modules/**
* **/bower_components/**
* coverage/**
* {tmp,temp}/**
* **/*.min.js
* **/bundle.js
* fixtures{-*,}.{js,jsx}
* fixture{s,}/**
* {test,tests,spec,__tests__}/fixture{s,}/**
* vendor/**
* dist/**
* lintText now throws when providing opts.ignores without opts.filename

feat: apply `.ignores` to `lintText`

---

index.js
options-manager.js
test/.gitignore
test/bar/.gitignore
test/options-manager.js

*  split out getGitIgnores from getIgnores
*  adapt test cases accordingly
*  extend gitignore test case with negative pattern
*  invert gitignore patterns and feed sotred as glob instead of opts.ignore
fix #154

Handle negative gitignore patterns correctly

---

options-manager.js
package.json
test/cli.js
test/options-manager.js

* Depends on #201 
* Credits for original bugfix go to @schnittstabil

Parse nested gitignores correctly

---

cli.js

This PR adds support for the `--open` CLI option with VS Code as your `$EDITOR`. Adding the `--goto` option, VS Code will support the `path:line:column` format to open files at the specified line/column.

Add VS Code support for `--open`

---

cli.js
index.js
options-manager.js
readme.md
test/api.js
test/fixtures/cwd/unicorn.js

The `cwd` option has already been used by multiple tests, but was implemented erroneously.

Fix and document `cwd` option

---

test/api.js
test/fixtures/gitignore-multiple-negation/!!!unicorn.js
test/fixtures/gitignore-multiple-negation/!!unicorn.js
test/fixtures/gitignore-multiple-negation/!unicorn.js
test/fixtures/gitignore-multiple-negation/.gitignore
test/fixtures/gitignore-multiple-negation/unicorn.js

Multiple negated gitignore patterns (e.g. `!!unicorn.js`) were interpreted wrongly before #204. These tests ensure correct interpretation of future releases.
**Note:** Tests are failing because of #216

Add tests for multiple negated gitignore patterns

---

index.js

Currently if you just run `$ xo`, it globs all files and then filters out the supported files. We should instead create the default pattern based on the `extensions` option.

Don't glob everything when XO receives no patterns

---

readme.md

Hello :wave:
Starting in ESLint v4.1.0, ESLint now supports [config overrides based on glob patterns](http://eslint.org/docs/user-guide/configuring#configuration-based-on-glob-patterns) (with a design largely inspired by xo, I think). This commit updates the readme to remove the note about ESLint not supporting config overrides.

Update outdated note about config overrides

---

lib/options-manager.js

I know XO doesn't lint anything about `flow` by default which is great!
But I think it's a good idea to make XO ignores all files inside the `flow-typed` dir (generated by [flow-typed](https://github.com/flowtype/flow-typed)) by default

Add `flow-typed` dir to ignored path list

---

config/plugins.js

[babel-polyfill](https://babeljs.io/docs/usage/polyfill/) and [babel-register](https://babeljs.io/docs/usage/babel-register/) are common modules that doesn't need to assigned.
It would be convenient to have them ignored by the [import/no-unassigned-import](https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-unassigned-import.md) rule.

Exclude babel-register and babel-polyfill from no-unassigned-import

---

config/plugins.js
index.js
lib/gitignore.js
lib/options-manager.js
package.json
readme.md

Fixes #123
Add the following rules:
| Rule ID                                                                                                                     | Description                                                       |
| --------------------------------------------------------------------------------------------------------------------------- | ----------------------------------------------------------------- |
| [no-unpublished-bin](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-bin.md)         | Disallow 'bin' files which are ignored by npm                     |
| [no-unpublished-import](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unpublished-import.md)   | Disallow `import` declarations of private …

Add eslint-plugin-node

---

config/plugins.js
index.js
lib/options-manager.js
main.js
package.json
readme.md
test/fixtures/engines/package.json
test/main.js
test/options-manager.js

This allow to enable specific rules/rules configuration based on the range defined in `engines` field in `package.json` or the `nodeVersion` option.
If `nodeVersion` is set to `false` then the old behavior is resumed: no Node version specific rules are enabled.
The following rules are enable:
- `promise/prefer-await-to-then` for Node 8 and above
- `prefer-rest-params` for Node 6 and above
- `prefer-spread` for Node 5 and above
- `prefer-destructuring` for Node 6 and above
Should I add more?
We could later add [node/no-unsupported-features](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-features.md) by passing the value `opts.nodeEngine` in the [version option](https://github.com/mysticatea/eslint-plugin-node/blob/master/docs/rules/no-unsupported-feat …

Enforce rules based on "engines" field in package.json

---

config/plugins.js
package.json

Related sindresorhus/eslint-config-xo#45
Fix #282
I added the plugin and rules suggested in #282. I didn't add the `--jsdoc` option for the reasons explained in [this comment](https://github.com/sindresorhus/xo/issues/282#issuecomment-356035657):
> As the `valid-jsdoc` rule is used when a JSDoc bloc is defined, in the end the `jsdoc` flag would just enable the `require-jsdoc` rule forcing to write JSDoc for every declaration in the code.
> Enforcing 100% JSDoc is not really something very common from what I see in the open source community (AFAIK ESLint is the only major project with near 100% JSDoc coverage).
> In addition, it would be difficult to find the best default config for the rule. Some might want a warning, some an error. Some might want a JSDoc block for function expression …

Add JSDoc plugin

---

config/plugins.js
package.json

Per [comment](https://github.com/sindresorhus/xo/issues/282#issuecomment-359282802) those new rules have several bugs.
```js
/**
* Sentence with a word stating with a
* Capital letter.
*/
```
Returns an error, even though it should be valid to break the line and sometimes the break happen before a capitalize word.
```js
/**
* List of things:
* - elem 1
* - elem 2
*/
```
Returns an error even though doing a list should be perfectly valid in JSDoc.
```js
/**
* Code example:
* ```js
* console.log(test)
* ```
*/
```
Once again returns an error even though perfectly valid.
All the following situation might create an issue:
- Using capital letter in the middle of a sentence
- Using list
- Using colon (`:`) + new line to describe something
- Using code example
- Using mardown
We should remove …

Revert JSDoc plugin

---

lib/options-manager.js
test/options-manager.js

Disabling due to eslint/eslint#9970

Disable `enforceForRenamedProperties` for `prefer-destructuring`

---

main.js

It's `meow` set all boolean option to `false` if they are not set.
That means all boolean options set in `package.json` will be overwritten.
The `semicolon` options is commented out for this reason. The `pretiter` one is in the same situation...

Disable parsing of prettier CLI option

---

lib/options-manager.js
test/options-manager.js

In the specific case of both `prettier` and `space` being `true`, the indent rules is customized by XO.
Rules defined in the `rules` property override the one defined in a config file (in this case `eslint-config-prettier`). So it ends up in a situation in which the number of space to use is handled by both `prettier` and the eslint `indent` rules. In some cases it creates a conflict.
With this change the `indent` rule is set only when `prettier` is `false`.

Do not add indent rule when `prettier` option is true

---

lib/options-manager.js
test/options-manager.js

Default Prettier `trailingComma` conf to `none`

---

lib/options-manager.js

Initially I thought it would be a good idea, but turns out I actually want to lint most fixture files too.
For example, in AVA, we ended up having to explicitly specify it: https://github.com/avajs/ava/blob/a76d462b4cdccd86028e8c9b1bbf84f12af8ab84/package.json#L13
Another example, here it would also have been useful to lint fixtures: https://github.com/sindresorhus/electron-timber/pull/10#discussion_r186282242

Don't ignore fixture directories by default

---

lib/options-manager.js
package.json

https://eslint.org/blog/2018/06/eslint-v5.0.0-released

Upgrade to ESLint 5

---

code-of-conduct.md
contributing.md
readme.md

Just a little polishing:
* One page was moved to a new URL.
* A fragment link in the README needed to be updated.
* Most of the URLs can use `https` instead of `http`
* Links in the contributor covenant didn't match the source and one was unnecessarily specified twice (as the link text and as the href).
If you'd like any adjustments or want these commits squashed, just let me know!

Fix links in documentation

---

lib/options-manager.js
main.js
test/fixtures/engines-overrides/package.json
test/fixtures/engines-overrides/promise-then-transpile.js
test/fixtures/engines-overrides/promise-then.js
test/fixtures/engines/package.json
test/lint-files.js
test/lint-text.js
test/options-manager.js

With the following configuration:
```json
{
"xo": {
"nodeVersion": ">=6.0.0",
"overrides": [
{
"files": "**/transpile/**",
"nodeVersion": ">=8.0.0"
}
]
}
}
```
The files in `**/transpile/**` were wrongly analyzed with `nodeVersion: '>=6.0.0'` because the `nodeVersion` in `overrides` was ignored. The code was mistakenly expecting the option to be set with `engines: {node: '>=8.0.0'}`.
With this PR the config above works as espected.

Respect `nodeVersion` option set in `override` block

---

main.js
test/fixtures/space/one-space.js
test/fixtures/space/two-spaces.js
test/main.js

Overview
========
Ensure that the `space` value, if present, is either a number or a boolean before passing it to the main API.  The space option is intended to act as either a boolean or a number option, but it is implemented as a string option out of necessity, which led to a few bugs.
Bugs fixed
----------
Here are the results of several invocations before and after applying this PR:
* Expect 2-space indents.
* The value of `space` is the *string* `'4'`.
* The value is truthy, resulting in the space option being activated.
* The value is not a number, resulting in the default of 2 being used.
* Expect 4-space indents.
* The value of `space` is the *number* `4`.
* Check all files in the CWD and expect 2-space indents.
* The value of `space` is `'file.js'`.
* The value is truthy and not …

Fix CLI's `--space` option parsing

---

cli-main.js

An issue I ran into when writing an Emacs function for xo auto-fixing my buffer is when the stdin passed to xo has no code issues, the command `xo --stdin --fix` will return `undefined`, which is a pain in the side. This small fix should hopefully alleviate that with minimal side effects. 
I couldn't find any documentation stating that was to be the desired behavior, and I did find this issue with the same problem from a couple years back: https://github.com/xojs/xo/issues/245
Let me know if I'm PR-ing the wrong project, and I should be investigating ESLint instead!

Make `--stdin --fix` always return the code even if nothing was fixed

---

index.js
test/cli-main.js

 Turn all paths `cwd`-relative before linting

---

readme.md

Fixed a typo in the readme from "You'll need eslint-onfig-xo-vue" to "You'll need eslint-config-xo-vue".

Fix typo in eslint-config-xo-vue link

---

lib/options-manager.js

This disable the rule `unicorn/no-nested-ternary` when Prettier formatting is enabled.
The reason is that currently Prettier doesn't allow to wrap nested ternary in parenthesis. See https://github.com/prettier/prettier/issues/4157.
This rule can be re-enabled if https://github.com/prettier/prettier/issues/4157 is fixed to allow those parenthesis.

Disable `no-nested-ternary` when Prettier is used

---

readme.md

I've created a basic webpack plugin for XO to be used. This is brand new - I was having trouble with the loader one and wanted it to be simpler to install and use. I have plans to add more features as well - but I wanted to get this link up on XO.

Add webpack plugin to the readme

---

config/plugins.js
lib/options-manager.js

`Array.flatMap` is available only on Node.js >= 11: https://node.green/#ES2019-features-Array-prototype--flat--flatMap--Array-prototype-flatMap

Enable `unicorn/prefer-flat-map` only for Node.js >= 11

---

index.js
lib/options-manager.js

Support for object spread didn't actually land until Node.js 8.3.0
ref: https://node.green/#ES2018-features-object-rest-spread-properties-object-spread-properties

Fix Node.js range for `prefer-object-spread` rule

---

cli-main.js

This let's the process exit in the same way but still allows the streams to finish before `child_process` kills it.
Ref: https://github.com/nodejs/node/issues/12921

Fix compatibility with being run in a child process

---

lib/options-manager.js
test/options-manager.js

Use the new plugin specific override from https://github.com/prettier/eslint-config-prettier

Use new eslint-config-prettier override

---

config/plugins.js
lib/options-manager.js
test/lint-files.js
test/lint-text.js
test/options-manager.js

This PR change how the internal logic works regarding the `nodeVersion`. Instead of disabling rules by default and enabling them based on the version we now do the opposite.
That allow us to define whatever rules we like regardless of the Node version and then disable some based on the user's node version.
This way we won't have to change anything when we increase the minimum Node version supported by XO !
For XO users it doesn't change anything.
Fix #421

Disable rules based on Node.js version

---

config/plugins.js
lib/options-manager.js
readme.md
test/options-manager.js

Fix #108
The following rules are added, only if the `node-version` is used or if the `package.json` has a valid `engines.node` prop:
- `node/no-unsupported-features/es-builtins`
- `node/no-unsupported-features/es-syntax`
- `node/no-unsupported-features/node-builtins`

 Add `node/no-unsupported-features` rules and fix unit tests

---

lib/constants.js
lib/options-manager.js
test/options-manager.js

Fix #392 
This should be a breaking change as it changes how the overrides are resolved.
The values of `extends`, `envs`, `globals` and `plugins` for overrides are are now the concatenation of the override and the global config.

Fix overrides handling for `extends`, `envs`, `globals`, `plugins`

---

lib/options-manager.js

Follow up to #431
On large project the order of files passed to the `getTsConfigCachePath` can vary from one run to the other, which result in a different tsconfig temporary file name, invalidating the ESLint cache.
This PR applies a sort to the files list to maintain a consistent file name.
Sorry about all the different PRs to finally get that functionality right...

Sort files path before generating unique cache key

---

index.js
lib/options-manager.js
package.json
test/fixtures/config-files/xo-config/file.js
test/fixtures/config-files/xo-config_js/file.js
test/fixtures/config-files/xo-config_json/file.js
test/fixtures/config-files/xo_config_js/file.js
test/lint-files.js
test/lint-text.js
test/options-manager.js

Get `extensions` and `ignores` from config files

---

config/plugins.js
package.json

See: https://github.com/sindresorhus/eslint-plugin-unicorn/blob/master/docs/rules/string-content.md
Anything else useful we can enforce in strings?
// @pvdlg @fregante

Add `unicorn/string-content` rule

---

lib/options-manager.js
package.json
readme.md
test/fixtures/webpack/no-config/file1.js
test/fixtures/webpack/no-config/file2.js
test/fixtures/webpack/no-config/file3.js
test/fixtures/webpack/with-config/file1.js
test/fixtures/webpack/with-config/file2.js
test/fixtures/webpack/with-config/webpack.config.js
test/lint-files.js
test/options-manager.js

Add `webpack` option

---

lib/options-manager.js
test/options-manager.js

Fix #438 
This also correctly removes the `parser` option set by the user for the Typescript files, so the option doesn't conflict with `@typescript-eslint/parser`.

Add `xo-typescript` and `prettier/@typescript-eslint` before user extends

---

lib/options-manager.js
test/options-manager.js

Per https://github.com/xojs/xo/pull/446#discussion_r402357614
This essentially revert #451 and #442 that weren't the correct fixes.
Instead we now add the typescript specific extends after the base XO config and before the user extends.
This allow `eslint-config-xo-typescript` to override some rules from `eslint-config-xo` and users to extend a config that override rules from both `eslint-config-xo-typescript` and `eslint-config-xo`.
@EdJoPaTo can you confirm this fix the issues reported?

Add TS extends after base XO extends and before user extends

---

lib/options-manager.js
test/options-manager.js

Fix #456 
In case no `engines.node` don't set `nodeVersion` as `undefined` so it can be overridden by `nodeVersion` set in XO config.

Allow `nodeVersion` in XO config to override `engines.node`

---

config/plugins.js

Not all strings are user-facing so a blanket "replace all ... with …" can break all non-tagged strings.
As reported in https://github.com/xojs/xo/pull/439#issuecomment-598751860

Temporarily disable the `unicorn/string-content` rule

---

lib/constants.js

The next version of tap will be using the `.cjs` extension for
compatibility with packages that have `"type": "module"`.
Ref #384

Add `tap-snapshots/*.cjs` to default ignore list

---

cli-main.js
test/cli-main.js

Prevent extraneous newline from `--stdin --fix`

---

lib/options-manager.js
test/options-manager.js

This pull request fixes #479 by adding a check to see if the name of the module starts with `@`. If so, it'll return the name and attempt to resolve the module as is.
I've added to the "buildConfig: extends" test for testing. I've also tested and confirmed that this works in my own project using a scoped module.
It's worth noting that eslint accepts `@scope`, `@scope/eslint-config`, and `@scope/eslint-config-my-config` with the extends option ([docs](https://eslint.org/docs/developer-guide/shareable-configs#npm-scoped-modules)). The goal of this PR is to allow for these cases to be used just as they can be in an eslint config.

Add support for scoped shareable configs

---

config/plugins.js

https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-anonymous-default-export.md
Reports:
```js
export default () => {}
export default class {}
export default function () {}
```
Function names help automatic imports by IDEs
---
https://github.com/benmosher/eslint-plugin-import/blob/master/docs/rules/no-named-default.md
Reports: 
```js
// message: Using exported name 'bar' as identifier for default export.
import { default as foo } from './foo.js';
import { default as foo, bar } from './foo.js';
```

Enable `import/no-anonymous-default-export` and `import/no-named-default`

---

.travis.yml

Node v14 has been [current since April](https://github.com/nodejs/Release). It would be a good idea to test against the current version of node.
I understand there was an issue when v14 was first released, but it seems to have been fixed.

Test on Node.js 14

---

cli-main.js
package.json

Two major changes were introduced in v6:
1) The `autoVersion` option does not work with 2 arguments as it was used in the test, so we disable autoVersion and implement it ourselves.
2) The `alias` option does not seem to function as we were using it so we manually copy the `stdinFilename` option to `filename` when `stdin` is enabled.
Fixes #471

Update meow from v5.0.0 to v7.0.1

---

package.json
test/lint-text.js

There were 3 changes required to update the `ava` devDependency from `v1.1.0` to `v3.9.0`:
1) `ava` no longer automatically supports ESM syntax. We need to add `esm` to `devDependencies` and add some configuration to instruct `ava` to use the `esm` library.
2) The acceptable arguments for messages has been restricted to strings. In a two different tests the results object was used as the message. Removing the message matches the usage in the majority of tests.
3) The signature for the expectation argument in throws has changed and now requires an object. In one case a regex was used. Moving the regex into the `message` property on resolved the issue.

Update devDependency ava from v1.1.0 to v3.9.0

---

lib/options-manager.js
test/options-manager.js

The `prettier` CLI by [default](https://prettier.io/docs/en/cli.html#--no-editorconfig) reads [certain options](https://prettier.io/docs/en/api.html#prettierresolveconfigfilepath--options) from `.editorconfig` if they are present. We should respect them too under `"prettier": true`. This is a simple matter of passing the appropriate flag to `prettier.resolveConfig`.

Respect Prettier’s use of .editorconfig

---

cli-main.js

Closes #465 
I tested locally and the logic seems correct:
```
❯ xo
index.js:10:15
✖  10:15  Multiple spaces found before =.  no-multi-spaces
✖  11:41  Missing semicolon.               semi
2 errors
❯ export GITHUB_ACTIONS=true
❯ xo
./index.js: line 10, col 15, Error - Multiple spaces found before '='. (no-multi-spaces)
./index.js: line 11, col 41, Error - Missing semicolon. (semi)
2 problems⏎
```
However I don't know if this actually works on GHA. The syntax that appears on GHA (as shown in #465) is not this one.

Enable automatic annotations on GitHub Actions

---

package.json

Closes #500
After using the Yarn resolutions method in the linked issue for a while, I haven't noticed anything breaking by upgrading Prettier.
This will bring TypeScript v4 support to Prettier.
As a note, this doesn't fix #466 but it seems somebody has found the cause and outlined some possible solutions in this comment: https://github.com/xojs/xo/issues/483#issuecomment-722618023

Bump Prettier to ^2.1.2

---

config/plugins.js
test/lint-text.js

Xo is often used in Webpack front end repositories, although `import/no-unassigned-import` rule, by default, denies style-sheets imports, it's important to allow unassigned imports of the most common style-sheet extensions.

Allow unassigned stylesheet imports

---

cli-main.js

https://github.com/dersimn/issue-xo
`package.json`:
```json
{
"devDependencies": {
"xo": "^0.36.1"
},
"xo": {
"space": 4,
"globals": [
"myGlobalFunction"
]
}
}
```
`index.js`:
```javascript
function something(foo) {
myGlobalFunction(foo);
}
something();
```
1) `npx xo`
- Runs without errors
2) `cat index.js | npx xo --stdin`: 
- Returns: `✖  2:5  myGlobalFunction is not defined.  no-undef`
- However the `space: 4` option is respected.
- `cat index.js | npx xo --globals myGlobalFunction --stdin` works
- Maybe because `rules` are simply forwarded to eslint and all other options are parsed by XO ?
This issue occurred first on update from [`v0.34.2` to `v0.35.0`](https://github.com/xojs/xo/compare/v0.34.2...v0.35.0). 
The issue seems to be the update from `"meow": "^7.1.1"` to `"meow": …

Fix ignored package.json config when using the CLI

---

lib/options-manager.js

Disable the `node/file-extension-in-import` rule for TypeScript projects

---

package.json
readme.md

With this PR I change the description in `readme.md`(1st phrase) and in `package.json`, from:
`JavaScript/TypeScript linter with great defaults` to:
`JavaScript/TypeScript linter (ESLint wrapper) with great defaults`
in order to better clarify/stand out that xo uses ESLint underneath, an already very popular and widely used JavaScript linter,
and that it's not a linter itself, like JSLint, JSHint, ESLint, etc,
something that might discourage a new user from trying it, if he sees it for the first time, and has never heard of it.
Currently, searching in GitHub and npmjs, 
the description, as it is, and the tags used in npmjs, 
might all give the wrong impression that it's the opposite:
screenshots:
<details>
<summary>GitHub search</summary>
</details>
<details>
<summary>npmjs …

Mention in project description that XO is an ESLint wrapper

---

cli-main.js
index.js
readme.md
test/cli-main.js
test/lint-files.js
test/lint-text.js
test/open-report.js
test/print-config.js

I often find myself needing this option to figure out which rules XO is using. If I learn about a new ESLint rule, I want to be able to check whether XO already enables it or something similar; if I upgrade XO, I want to be able to check whether it disabled any rules I was relying on; I want to be able to check that I configured `overrides` correctly and that it’s applied in the order I expect; etc.
This was largely based on #312 by @teehemkay.

Add `--print-config` flag

---

cli-main.js
index.js
lib/constants.js
lib/options-manager.js
package.json
test/lint-text.js
test/options-manager.js
test/print-config.js

Using ESLint's config resolver appears to have fixed something: https://github.com/xojs/xo/pull/534/files#diff-c7ac45885b6a1731e12a1b86ded6b01081581db88a5a625c7b96c222cf05db95L412-R431
Fixes #474

Move from deprecated `ESLint.CLIEngine` to `ESLint`

---

index.js

Tiny changes of code I noticed in https://github.com/xojs/xo/pull/534/files

Avoid destructuring and just build the expected object once

---

index.js
lib/constants.js

Remove some needless imports

---

lib/constants.js
readme.md
test/fixtures/config-files/xo-config_cjs/.xo-config.cjs
test/fixtures/config-files/xo-config_cjs/file.js
test/fixtures/config-files/xo_config_cjs/file.js
test/fixtures/config-files/xo_config_cjs/xo.config.cjs
test/lint-files.js
test/lint-text.js

- Fixes `ERR_REQUIRE_ESM` error from `cosmiconfig`.
- Enables using `xo.config.cjs`/`.xo-config.cjs` in ESM packages with `"type": "module"`.
Fixes #468.
See
- https://github.com/xojs/xo/issues/468
- https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
Sample error output; problem fixed by this commit.
```text
Error [ERR_REQUIRE_ESM]: Must use import to load ES Module: /my-code/.xo-config.js
require() of ES modules is not supported.
require() of /my-code/.xo-config.js from /my-code/node_modules/cosmiconfig/dist/loaders.js is an ES module file as it is a .js file whose nearest parent package.json contains "type": "module" which defines all .js files in that package scope as ES modules.
Instead rename .xo-config.js to end in .cjs, change the requiring code to use import(), …
```

Support `xo.config.cjs` and `.xo-config.cjs`

---

lib/options-manager.js
test/options-manager.js

Fixes #338
---
<details>
<summary>
<b>IssueHunt Summary</b>
</summary>
This pull request has been submitted to:
- [#338: Should the `useEslintrc` option be documented?](https://issuehunt.io/repos/40053602/issues/338)
---
</details>

Prevent the `useEslintrc` option from being used

---

lib/options-manager.js
readme.md
test/options-manager.js

When running `xo --prettier`, the `trailingComma` is controlled by Prettier, the `comma-dangle` rule will be disabled, 
The `trailingComma: 'all'` behave the same as [the comma-dangle option in `eslint-config-xo`](https://github.com/xojs/eslint-config-xo/blob/main/index.js#L17-L18).
If user want different behaviour, instead of changing `comma-dangle`, user should override Prettier's option.
Fixes #579

Change `trailingComma` option for Prettier to `all`

---

cli.js
test/cli.js

When running `xo --print-config` without a filename, the CLI actually running lint instead of throw an error.

Fix running `xo --print-config` without a filename

---

readme.md

Since it was reorganized in [Google Season of Docs.](https://eslint.org/blog/2020/08/eslint-google-season-of-docs-project-writer)

Fix some broken links for ESLint docs

---

lib/options-manager.js
package.json
test/options-manager.js

The usage of `fs-extra` is only related to reading/writing JSON currently, then they can be replaced with some combinations of native modules to reduce the dependency.

Remove `fs-extra` dependency

---

lib/options-manager.js
package.json

Remove some replaceable/unused dependencies.

Drop some moot dependencies

---

config/plugins.cjs
lib/options-manager.js
test/options-manager.js

Enable `import/named` rule for JavaScript

---

lib/options-manager.js
readme.md
test/fixtures/prettier/package.json
test/options-manager.js

`jsxBracketSameLine` was deprecated in prettier 2.4.0.

Replace Prettier's `jsxBracketSameLine` option with `bracketSameLine`

---

config/plugins.cjs

Arrays don't necessarily need to be named `list`. These lists are can just be named allow/allowed/include or exclude/except/exclusions. `deny` itself feels kinda awkward too because it usually applies to "access" only, not other kinds of generic exclusions lists.

Rename allowList/denyList in `prevent-abbreviations`

---

config/plugins.cjs

I think this config should be dropped. Reasons:
- it actually "breaks" the rule for .ts/tsx files because it allows them to be imported without extension
1. create `file.ts`
2. `import './file'` in `another.ts`
3. No errors! 😰 
- it duplicates TypeScript’s own error, but with a worse message:

Enforce extensions on TypeScript files as well

---

lib/options-manager.js
package.json
test/options-manager.js

[`esm-utils` v3.0.0](https://github.com/fisker/esm-utils/releases/tag/v3.0.0)

Update `esm-utils` to v3

---

readme.md

Add rule config override example

---

config/plugins.cjs
lib/constants.js
lib/options-manager.js
package.json
test/options-manager.js

move to eslint-plugin-n: https://www.npmjs.com/package/eslint-plugin-n. as the original one is no longer actively maintained(last version was released ~2y ago).
the fork has been adopted by standard.

feat!: switch to eslint-plugin-node's maintained fork

---

cli.js
index.js
lib/report.js
test/lint-files.js
test/lint-text.js

Simple addition for use in the vscode extension. 
I had added a different package to get the rule docs, but it is broken for mono-repo based plugins, and this change was simpler than fixing the third party rule-docs package.
Note: we _may_ want to add a similar change to lintFiles as we currently construct our urls in eslint-formatter-pretty with the broken package I mentioned. 
related to: https://github.com/xojs/vscode-linter-xo/issues/112

include rulesMeta by default for all linting

---

lib/options-manager.js
test/options-manager.js

@sindresorhus Under windows some tests on file names did not match because they were compared with different directory separators. This PR fixes this issue using the `slash` lib where it was required for my case, it is possible that for other configurations (under windows) it should be done elsewhere as well.
Fixes https://github.com/sindresorhus/type-fest/issues/451

Fix windows directory  separator

---

readme.md

Update XO badge

---

index.js

Remove unnecessary `isGitIgnoredSync` call.
Files ignored by `.gitignore` already checked when globbing files https://github.com/xojs/xo/blob/b15cbfed6e7db7100158fc9d614b69621449604e/index.js#L31

Improve `lintFiles`

---

package.json

Among other improvements, this fixes a crash in the `@typescript-eslint/unified-signatures` rule: typescript-eslint/typescript-eslint#6940.
(Alternatively, since Node.js 14 reaches [end-of-life](https://github.com/nodejs/Release#release-schedule) this weekend, maybe we can revert #624 so that users can get the latest typescript-eslint independently again?)

Upgrade bundled typescript-eslint

---

config/plugins.cjs
lib/constants.js
readme.md
test/fixtures/typescript/child/extra-semicolon.cts
test/fixtures/typescript/child/extra-semicolon.mts
test/lint-files.js

Fixes #633.
Not sure if there's any other changes that need to be made.

Add new TypeScript extensions (`.mts`, `.cts`)

---

readme.md

From https://github.com/typescript-eslint/typescript-eslint/tree/main/packages/parser#parseroptionsproject
To https://typescript-eslint.io/packages/parser/#project

Update tsconfig project link

---

readme.md

The new parameter `logoSize=auto` was added in https://github.com/badges/shields/pull/9191
We can have a better visual now.
```
https://shields.io/badge/code_style-5ed9c7?logo=xo&labelColor=gray
https://shields.io/badge/code_style-5ed9c7?logo=xo&labelColor=gray&logoSize=auto
https://shields.io/badge/code_style-5ed9c7?logo=xo&labelColor=gray&logoSize=auto&logoWidth=20
```
Which one would you prefer?
I will update https://github.com/xojs/xo/issues/689#issuecomment-1253127616 after you choose.

Polish XO badge

---

package.json

fixes #752
The current version of XO uses `eslint-plugin-n@16.x`, which invokes a deprecated method in Node.js v22. For more information about the exact cause and deprecated version, please see #752.
We can see a deprecation warning at the end of the report.
```ts
node cli.js
config/plugins.cjs:35:3
⚠   35:3  Unexpected todo comment: TODO: Remove this override at some....        no-warning-comments
⚠  141:3  Unexpected todo comment: TODO: Restore when it becomes safer:....      no-warning-comments
⚠  165:3  Unexpected todo comment: TODO: Disabled for now as I don't have....    no-warning-comments
⚠  177:3  Unexpected todo comment: TODO: Remove this override when the rule....  no-warning-comments
⚠  180:3  Unexpected todo comment: TODO: Temporarily disabled until it.... …
```

fix: update `eslint-plugin-n` to latest which no longer use deprecated method

---

lib/options-manager.js

- Fixes https://github.com/xojs/xo/issues/598
- Follows https://github.com/xojs/xo/pull/761
- Tested in https://github.com/refined-github/refined-github/pull/7588
This is confirmed to fix the issue. Also I was able to verify that setting `nodeVersion: "20"` in an override restores the node-related rules.

Respect `nodeVersion: false` option

---

config/plugins.cjs

fixes #763 
As far as I understand the updated rule checks for the listed extensions and only allows the listed ones now. `js` wasn't included and therefore assumed as forbidden.
As the rule was improved the reason for these custom options in gone now. It automatically assumes `js` for `ts` now.
https://github.com/eslint-community/eslint-plugin-n/blob/master/docs/rules/file-extension-in-import.md mentions `typescriptExtensionMap` but the default one seems to be fine so no need to configure it.

fix: restore typescript extension support

---

package.json
tsconfig.json

Publish d.ts files for use in editor extensions or `xo.config.{ts|js}` files.
Also a little tsconfig cleanup

chore: publish dts files

---

readme.md

The `logoWidth` has been removed since https://github.com/badges/shields/pull/10878.
I will update the comment https://github.com/xojs/xo/issues/689#issuecomment-1253127616 after this PR gets merged.

Update XO badge URL

---

package.json

Please correct me if I'm wrong.
It looks like we only used those source map files for testing purposes. Maybe we could ignore them while publishing to npm.

Ignore source map files while publishing

---

readme.md

Prettier changed the default from `'es5'` to `'all'` in v3: https://prettier.io/blog/2023/07/05/3.0.0.html

Remove `trailingComma`

---

cli.ts
lib/handle-ts-files.ts
lib/xo.ts
scripts/setup-tests.js
test/helpers/copy-test-project.ts
test/xo/lint-text.test.ts

- fixes a bug when one xo instance is used to run `lintText` multiple times, where some ts rules would get stripped after the first lint run. We now clone the config before each run.
- fixes matching on tsconfig files by using `contains` instead of `isMatch` from micromatch. This fixes matching on 'node_modules' which is common on excludes. I think `isMatch` may still be correct for `files` and `include`.
- removes `files` from tsconfigs during test. This doesn't change anything for tests.
- `lint-text` is more reliable for ts files when the file is written to disk, which we now do. This fixed some issues of getting different results between ubuntu and mac. 
- correctly use `find-cache-directory` for ts files --stdin caching

fix: ensure lint text does not strip rules between runs

---

lib/xo.ts
test/xo/lint-text.test.ts

Because of the `structureClone` introduced in #802, configs with custom plugins fail to load, since custom plugins have functions in them.
This PR removes the use of `structureClone` and replaces it with the approach mentioned in [this comment](https://github.com/xojs/xo/pull/802#issuecomment-2918727459).

Fix: Error while loading configs with custom plugins

---

lib/handle-ts-files.ts
test/cli.test.ts

Noticed that our logic was having some issues with nested tsconfigs
So this PR:
uses `getTsconfig` for every file, due to lots of internal caching this appears to be very fast still and behaves much more like ts lang server does by finding the nearest tsconfig.json rather than just looking in the root. 
uses get-tsconfigs file matcher which is much more accurate than our custom logic based on micromatch. 
We no longer attempt to re-use any of the users tsconfigs if they are matched, we only write our own default tsconfig for unmatched files. This should provide a more consistent xo experience.
Added a few tests for nested configs and edge cases.

Use get-tsconfig for ts matching

---

cli.ts
test/cli.test.ts

Fixes #815.
Resolves the file path passed to `print-config` before calling `calculateConfigForFile`.
Also, adds a test for when no path is provided.

Fix: Behaviour of `print-config` option with relative file path

---

lib/xo-to-eslint.ts
test/xo-to-eslint.test.ts
test/xo/lint-files.test.ts

Set `space: true` or `space: 2` in the `xo.config.js`, and use the code below for linting:
```js
console.log('hello'
+ 'world');
```
XO will report an `Expected indentation of 1 tab (@stylistic/indent-binary-ops)` error.
The linting process should pass.
I've added the `@stylistic/indent-binary-ops` rule below the `@stylistic/indent`.

Fix `indent-binary-ops` configuration for spaces
